### ISSUE TITLE
Token on json response

### ISSUE THREAD

**Issue by Melfo01** [eljam/guzzle-jwt-middleware#15]
In JWTManger, it's possible to change the `token_key` on parameters.

This library considered that the token has returned on the first level of the json response, but I need to treat a different response.
For example,the botpress response for connexion API : 
```
{
    "status": "success",
    "message": "Login successful",
    "payload": {
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJvdHByZXNzQGN5YmVybWFsdmVpbGxhbmNlLmdvdXYuZnIiLCJzdHJhdGVneSI6ImRlZmF1bHQiLCJpc1N1cGVyQWRtaW4iOnRydWUsImlhdCI6MTU2MzI3NzEzMSwiZXhwIjoxNTYzMjk4NzMxLCJhdWQiOiJjb2xsYWJvcmF0b3JzIn0.mYwBOjgLxlVduNuxzDUnIzMCE4oAQ5TMLLhK56XDdO4"
    }
}
```

How I can configure JWTManager to treat this connexion response? I think we need to do a pull request to change [l.118](https://github.com/eljam/guzzle-jwt-middleware/blob/master/src/Manager/JwtManager.php#L118) & [l.129](https://github.com/eljam/guzzle-jwt-middleware/blob/master/src/Manager/JwtManager.php#L129)

**Comment by eljam** [comment]
Hello,

Thanks for the issue. Looks like we will need something like property accessor component from symfony to help or something like behatch extension does where you can use javacript object style notation.
Like `payload.token` to access the value.

The line you pointed are the right ones.

My idea would be to extract the code complexity and use another class. Something like `TokenGuesser.php` to get the value from different path for token expiration and token value.

Do you think, you could make a proposal for this one ?

**Comment by Melfo01** [comment]
Hello,

I’m agree with you about extracting the code complexity to an another class and use the property accessor component.

Do you think, we need to change the constructor to replace $options by TokenGuesser ? If we do this, a major release is required.
Or do you prefer the other option and don’t change the constructor parameters and create TokenGuesser on it ?

I’ll see what and when I can do a proposal. But feel free to do it if you have more time than me ;)

**Comment by eljam** [comment]
Got a new computer, will try to work on this next week.

**Comment by eljam** [comment]
i've got a new PR for this behavior.

https://github.com/eljam/guzzle-jwt-middleware/pull/16

**Comment by nreynis** [comment]
Seems great! In the meantime we solved our problem by adding a middleware which normalized the payload before handling it to this one.

But this sure seems like a cleaner approach.

**Comment by eljam** [comment]
Everything has been merged and tag on a 0.7.0 version !

**Comment by eljam** [comment]
is it ok for you guys, can i close the issue ?

**Comment by eljam** [comment]
cool 👍
