### ISSUE TITLE
Token sometimes re-used too close to expiration.

### ISSUE THREAD

**Issue by alexander-aleman** [eljam/guzzle-jwt-middleware#24]
Hi,

I'm running into an issue that a token is re-used very close to the expiration of the token, which then cause a not-authorized response from the API.

I believe this is caused by the following line of code:
https://github.com/eljam/guzzle-jwt-middleware/blob/5df8e6e7be9c087cd34747c70d7844137f35fcaf/src/Manager/JwtManager.php#L135

or you could argue that this should be handled in the validation part:
https://github.com/eljam/guzzle-jwt-middleware/blob/5df8e6e7be9c087cd34747c70d7844137f35fcaf/src/JwtToken.php#L53

In my case I have solved this for now by adding a small safety margin:

```diff
--- a/src/Manager/JwtManager.php	2022-11-23 10:01:15.148041661 +0100
+++ b/src/Manager/JwtManager.php	2022-11-23 10:00:33.247774501 +0100
@@ -132,7 +132,7 @@
         }

         if ($expiresIn) {
-            $expiration = new \DateTime('now + ' . $expiresIn . ' seconds');
+            $expiration = new \DateTime('now + ' . ((int)($expiresIn * 0.9)) . ' seconds');
         } elseif (count($jwtParts = explode('.', $tokenValue)) === 3
             && is_array($payload = json_decode(base64_decode($jwtParts[1]), true))
             // https://tools.ietf.org/html/rfc7519.html#section-4.1.4
```

Perhaps you could think of a more elegant solution.

**Comment by michielkalle** [comment]
I agree, I have the same issue.

Example:
```php
return (new \DateTime('now + 1 seconds')) < $this->expiration;
```
