### ISSUE TITLE
Not work ...

### ISSUE THREAD

**Issue by jewome62** [eljam/guzzle-jwt-middleware#5]
Sorry for the title, i have not inspiration.
I try to debug but i don't understand.

I write some beautiful class for use it but that not work. And i try to look like your exemple on readme for test if I forget something but that not work.

PS : the class have inheriance with Client of Guzzle
```php
(into a class i have)
      $authStrategy = new FormAuthStrategy([
            'username' => $this->username,
            'password' => $this->password
        ]);

        //Create the JwtManager
        $jwtManager = new JwtManager($this, $authStrategy, [
            'token_url' => 'app_dev.php/api/post/en_GB/login_check'
        ]);

        // Create a HandlerStack
        $stack = HandlerStack::create();
        $stack->push(new JwtMiddleware($jwtManager));

        $client = new Client(['handler' => $stack, 'base_uri' => 'http://local.dev']);
        try {
            $locale = 'en_GB';

            $authorInfo = [
                'firstname' => 'test',
                'lastname' => 'test',
                'email' => 'test'
            ];

            $response = $client->post('app_dev.php/api/post/'.$locale.'/author/post.json', [
                'form_params' => [
                    'api_author' => $authorInfo
                ]
            ]);

            echo($response->getBody());
        } catch (TransferException $e) {
            echo $e->getMessage();
        }
```

Result: 
I have a good call to login api, I have a success with a token (see with some dump into class)
But for the call to post.json, i have not the Authorization Header ! and i have 401 (see into profiler of distant call)

I add some dump() into Guzzle code for understand, and I see the token once for the call but I don't understand how Guzzle work. Too many callback with Guzzle and Promise.

```bash
root@qanda:/var/www/qanda# composer show | grep guzzle
Do not run Composer as root/super user! See https://getcomposer.org/root for details
eljam/guzzle-jwt-middleware              v0.4.0              A jwt authentication middleware for guzzle 6
guzzle/guzzle                            v3.8.1              Guzzle is a PHP HTTP client library and framework for building RESTful web service clients
guzzlehttp/guzzle                        6.2.2               Guzzle is a PHP HTTP client library
guzzlehttp/promises                      1.3.0               Guzzle promises library
guzzlehttp/psr7                          1.3.1               PSR-7 message implementation
kevinrob/guzzle-cache-middleware         v1.4.3              A HTTP/1.1 Cache for Guzzle 6. It's a simple Middleware to be added in the HandlerStack. (RFC 7234)
```

Have you test the POST call ? do you have any idea ?

Thanks

**Comment by jewome62** [comment]
A trace of dump

We have a client for my second request (the post on Author)
The JWTMiddleware are called
I Have a token into JWTMiddleware

But the request prepare does not have the token

![image](https://cloud.githubusercontent.com/assets/472429/20791456/7100717e-b7bd-11e6-854b-c81ca877a0f8.png)

**Comment by eljam** [comment]
hi @jewome62, happy to help you.

You can see how i use it in a sdk that wraps the jwtMiddleware in a existing client. 
https://github.com/hogosha/sdk/blob/master/src/Api/Client.php
