### ISSUE TITLE
Renewal of tokens didn't work.

### ISSUE THREAD

**Issue by Wuffz** [eljam/guzzle-jwt-middleware#6]
The isValid function was never called, cause the token was fetched outside the closure for the middleware:

this fixed it for me:
`

public function __invoke(callable $handler)

    {
        $manager = $this->jwtManager;
        // echo $token; 
        // exit; 
        return function (
            RequestInterface $request,
            array $options
        ) use (
            $handler,
            $manager
        ) {
            $token = $manager->getJwtToken()->getToken();
            return $handler($request->withHeader(
                'Authorization',
                sprintf(self::AUTH_BEARER, $token)
            ), $options);
        };
    }
`

**Comment by eljam** [comment]
good catch !

**Comment by eljam** [comment]
Fixed in v0.4.1
