### ISSUE TITLE
Rebrand package

### ISSUE THREAD

**Issue by coudenysj** [eljam/guzzle-jwt-middleware#7]
As far as I can read, this package is a more generic Bearer token middleware :).

Maybe this should be stated more clear in the readme?

**Comment by eljam** [comment]
Hello,

You could see that as a Bearer token middleware but it cannot be use with oauth2 for example, we are missing some features.

Jwt is more simple as you can use jwt with oauth2 though.

Thanks for the PRs

**Comment by coudenysj** [comment]
Fair point :)
